-- begin HUNGRY_DISH
alter table HUNGRY_DISH add constraint FK_HUNGRY_DISH_ON_STORE foreign key (STORE_ID) references HUNGRY_STORE(ID)^
create index IDX_HUNGRY_DISH_ON_STORE on HUNGRY_DISH (STORE_ID)^
-- end HUNGRY_DISH
-- begin HUNGRY_ORDER_DETAIL
alter table HUNGRY_ORDER_DETAIL add constraint FK_HUNGRY_ORDER_DETAIL_ON_ORDER foreign key (ORDER_ID) references HUNGRY_ORDER(ID)^
alter table HUNGRY_ORDER_DETAIL add constraint FK_HUNGRY_ORDER_DETAIL_ON_STORE foreign key (STORE_ID) references HUNGRY_STORE(ID)^
alter table HUNGRY_ORDER_DETAIL add constraint FK_HUNGRY_ORDER_DETAIL_ON_DISH foreign key (DISH_ID) references HUNGRY_DISH(ID)^
create index IDX_HUNGRY_ORDER_DETAIL_ON_ORDER on HUNGRY_ORDER_DETAIL (ORDER_ID)^
create index IDX_HUNGRY_ORDER_DETAIL_ON_STORE on HUNGRY_ORDER_DETAIL (STORE_ID)^
create index IDX_HUNGRY_ORDER_DETAIL_ON_DISH on HUNGRY_ORDER_DETAIL (DISH_ID)^
-- end HUNGRY_ORDER_DETAIL
-- begin HUNGRY_ORDER
alter table HUNGRY_ORDER add constraint FK_HUNGRY_ORDER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table HUNGRY_ORDER add constraint FK_HUNGRY_ORDER_ON_STORE foreign key (STORE_ID) references HUNGRY_STORE(ID)^
create index IDX_HUNGRY_ORDER_ON_USER on HUNGRY_ORDER (USER_ID)^
create index IDX_HUNGRY_ORDER_ON_STORE on HUNGRY_ORDER (STORE_ID)^
-- end HUNGRY_ORDER
